use ploke_core::TrackingHash;
use serde::{Deserialize, Serialize};

use super::*;

/// Represents an unresolved item in the code.
///
/// This node is created when the parser encounters an import or re-export
/// that cannot be resolved to a known definition. This commonly happens
/// with items generated by macros like `include!` or when parsing incomplete
/// code snippets.
///
/// For example, in the `serde` crate, the `include!(concat!(env!("OUT_DIR"), "/private.rs"))`
/// macro generates a `serde_core_private` module at build time. Since the parser
/// doesn't expand `include!` macros, any `pub use serde_core_private::*;` statements
/// will create `UnresolvedNode` placeholders.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub struct UnresolvedNode {
    pub id: UnresolvedNodeId,
    /// The name of the unresolved item (last segment of the path)
    pub name: String,
    /// The full path that couldn't be resolved (e.g., ["crate", "serde_core_private", "Content"])
    pub path: Vec<String>,
    /// The span of the import/use statement that references this unresolved item
    pub span: (usize, usize),
    /// The visibility of the import/use statement
    pub visibility: VisibilityKind,
    /// The ID of the import node that references this unresolved item
    pub import_node_id: ImportNodeId,
    /// The ID of the containing module
    pub containing_module_id: ModuleNodeId,
    /// The reason why this item couldn't be resolved (for debugging)
    pub reason: UnresolvedReason,
    pub tracking_hash: Option<TrackingHash>,
    pub cfgs: Vec<String>,
}

/// Reasons why an item couldn't be resolved
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
pub enum UnresolvedReason {
    /// The item is from an `include!` macro that wasn't expanded
    IncludeMacroNotExpanded,
    /// The item is from a `macro_rules!` macro that wasn't expanded
    MacroRulesNotExpanded,
    /// The item is from an external crate that wasn't parsed
    ExternalCrateNotParsed,
    /// The item path couldn't be found in the module tree
    PathNotFound,
    /// Other reason (with description)
    Other(String),
}

impl UnresolvedNode {
    /// Returns the typed ID for this unresolved node.
    pub fn unresolved_id(&self) -> UnresolvedNodeId {
        self.id
    }

    /// Returns the full path as a string (e.g., "crate::serde_core_private::Content")
    pub fn path_string(&self) -> String {
        self.path.join("::")
    }
}

impl GraphNode for UnresolvedNode {
    fn any_id(&self) -> AnyNodeId {
        self.id.into()
    }

    fn visibility(&self) -> &VisibilityKind {
        &self.visibility
    }

    fn name(&self) -> &str {
        &self.name
    }

    fn cfgs(&self) -> &[String] {
        &self.cfgs
    }

    fn as_unresolved(&self) -> Option<&UnresolvedNode> {
        Some(self)
    }
}

impl HasAttributes for UnresolvedNode {
    fn attributes(&self) -> &[Attribute] {
        // Unresolved nodes don't have attributes
        &[]
    }
}
