[package]
name = "ploke-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31"                         # For the egui framework
egui = "0.31"
cozo = { workspace = true }
ploke-core = { path = "../ploke-core" } # For database access
thiserror = { workspace = true }        # Error handling
