# Clippy configuration for the workspace.
# We keep clippy::perf and clippy::nursery enforced in CI. This file tunes thresholds to reduce noise.
msrv = "1.77.0"

# Complexity thresholds (tweak to taste)
cognitive-complexity-threshold = 30
too-many-lines-threshold = 400
type-complexity-threshold = 200
enum-variant-size-threshold = 200
trivial-copy-size-limit = 32

# Allow underscores in doc links like `Vec<_>`
avoid-breaking-exported-api = false
