[book]
authors = ["ploke contributors"]
language = "en"
src = "src"
title = "Ploke Book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/josephleblanc/ploke"
edit-url-template = "https://github.com/josephleblanc/ploke/edit/main/docs/book/{path}"
