[package]
name = "ploke-expr"
version = "0.1.0"
edition = "2024"
description = "Expression parsing substrate for ploke"
authors = ["Joseph LeBlanc <joseph.t.leblanc@protonmail.com>"]

[dependencies]
proc-macro2 = { workspace = true }
tracing = { workspace = true }
drop_bomb = "0.1.5"
ra-ap-rustc_lexer = { version = "0.143", default-features = false }
rustc-literal-escaper = "0.0.4"
winnow = { version = "0.7.13", default-features = false }
rowan = "=0.15.17"

[dev-dependencies]
expect-test = "1.5.1"

[features]
default = []
in-rust-tree = []
