[package]
name = "syn_parser"
version = "0.1.0"
edition = "2021"
description = "A Rust code parser and analyzer using syn"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
# Parsing and code generation
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }

# Concurrency and parallelism
rayon = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }

# Data structures and algorithms
petgraph = { workspace = true }
cozo = { workspace = true }
# uuid is now an optional transitive dependency via ploke-core
uuid = { workspace = true, features = ["v5", "serde"] }

# Error handling
thiserror = { workspace = true }                          # version 2
ploke-common = { path = "../../common" }
ploke-core = { path = "../../ploke-core", features = [] } # Added dependency

# Added for Phase 1 Discovery (Optional)
toml = { version = "0.8" }
walkdir = { version = "2.4" }

cfg-expr = { version = "0.15" } # Main cfg parser, ensure features# handling cfg flags
target-lexicon = "0.12"         # For target configuration info


[dev-dependencies]
tempfile = "3.10" # For creating temporary files/dirs in tests

# Feature flags
[features]
default = [
    # "verbose_debug",
]
verbose_debug = []
# Post-MVP feature
workspace_vis = []
# Feature flag for the UUID refactor (REMOVED)
# Enables uuid_ids in ploke-core and brings in necessary discovery deps (REMOVED)
