[package]
name = "syn_parser"
version = "0.1.0"
edition = "2021"
description = "A Rust code parser and analyzer using syn"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
# Parsing and code generation
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }

# Concurrency and parallelism
rayon = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }

# Data structures and algorithms
petgraph = { workspace = true }
cozo = { workspace = true }
uuid = { workspace = true, features = [
    "v5",
    "serde",
], optional = true } # Keep workspace dep, make optional

# Error handling
thiserror = { workspace = true }         # version 2
ploke-common = { path = "../../common" }

# Added for Phase 1 Discovery (Optional)
toml = { version = "0.8", optional = true }
walkdir = { version = "2.4", optional = true }


[dev-dependencies]
tempfile = "3.10" # For creating temporary files/dirs in tests

# Feature flags
[features]
default = [
    # "verbose_debug",
]
verbose_debug = []
# Post-MVP feature
workspace_vis = []
# Feature flag for the UUID refactor
uuid_ids = ["dep:uuid", "dep:toml", "dep:walkdir"]
