[package]
name = "syn_parser"
version = "0.1.0"
edition = "2021"
description = "A Rust code parser and analyzer using syn"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
# Parsing and code generation
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }

# Concurrency and parallelism
rayon = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true }
dashmap = { workspace = true }

# Data structures and algorithms
petgraph = { workspace = true }
cozo = { workspace = true }
uuid = { workspace = true, features = ["v5", "serde"] }

# Error handling
thiserror = { workspace = true }
ploke-common = { path = "../../common" }

[dev-dependencies]

# Feature flags
[features]
default = [
    # "verbose_debug",
]
verbose_debug = []
# Post-MVP feature
workspace_vis = []
